//export const OBTENER_CUENTAS = 'OBTENER_CUENTAS';
//export const OBTENER_ERRORES = 'OBTENER_ERRORES';
export const GUARDAR_CUENTAS = 'GUARDAR_CUENTAS';
export const GUARDAR_TRANSFERENCIAS = 'GUARDAR_TRANSFERENCIAS';

